### ISSUE TITLE
Users can create ledgers

### ISSUE THREAD

**Issue by matthiasbeyer** [cashctrl/cashctrl#39]
* [ ] With initial amount of money in them, with preferred currency
* [x] But cannot edit the amount of money afterwards
* [x] But cannot edit the preferred currency afterwards
* [ ] Can change the name of the ledger afterwards

**Comment by TheNeikos** [comment]
Uhm, why can't you change the preferred currency?

**Comment by matthiasbeyer** [comment]
Kinda complicated... You would need to rewrite the whole transactions... Also we should talk of a currency of a ledger, not a _preferred_ currency.

Also, ledgers never change currency in real world, do they?

**Comment by TheNeikos** [comment]
Hm, I was thinking of creating a transaction that would withdraw all and re-submit it :)

But I agree it is not as elegant as 'never change'. And you are right, it is unlikely that it is a real use-case.

**Comment by matthiasbeyer** [comment]
There's one edge case, though: If you count your pocket as ledger and you move to another country...

Not sure wheter we should cover this as well...

**Comment by TheNeikos** [comment]
Yeah, but that's unlikely enough that I think users can figure that one out on their own :D

**Comment by matthiasbeyer** [comment]
Ack

**Comment by TheNeikos** [comment]
The fourth point is covered by #43
