### ISSUE TITLE
Ledgers: Option to verify that transactions do not result in negative amount in ledger

### ISSUE THREAD

**Issue by matthiasbeyer** [cashctrl/cashctrl#55]
A ledger should have an option which rejects transactions if the transaction results in a negative amount of money in the ledger.

**Comment by TheNeikos** [comment]
A few issues have cropped up while in dev:

What should happen if a transaction was erroneously added? Imagine you add 30 Euros, and take out 20 Euros and later realize you actually meant to add 3 euros? While this seems unlikely at first, if it does happen you have a large inconsistency in your money tracking. 


The accepted solution right now is to allow the user to go negative, but the ledger to be colored in a warning color, signalling that this is now negative.
