### ISSUE TITLE
Integrate Travis-CI

### ISSUE THREAD

**Issue by matthiasbeyer** [cashctrl/cashctrl#65]
Can be done as soon as there are a few tests.

**Comment by matthiasbeyer** [comment]
Test-Coverage foo could be integrated as well...

**Comment by TheNeikos** [comment]
What about a drone server on the studicloud?

**Comment by matthiasbeyer** [comment]
Could do that as well...

**Comment by TheNeikos** [comment]
I will do that then :)

**Comment by TheNeikos** [comment]
Looks like I cannot, however, you can do it as the owner, link: http://drone.studicloud.hs-furtwangen.de/

**Comment by matthiasbeyer** [comment]
The login link from the URL above does not work :-/

**Comment by TheNeikos** [comment]
Try again!

**Comment by matthiasbeyer** [comment]
I cannot integrate cashctrl/cashctrl, only matthiasbeyer/cashctrl.
