### ISSUE TITLE
Ledger#in_transactions doesn't work

### ISSUE THREAD

**Issue by matthiasbeyer** [cashctrl/cashctrl#69]
When doing:

```
Ledger.find(1).in_transactions
```

I get:

```
NameError: uninitialized constant Ledger::InTransaction
```

Seems like https://github.com/cashctrl/cashctrl/blob/master/app/models/ledger.rb#L4 is not complete.

I need that for #61

**Comment by matthiasbeyer** [comment]
Fixed with 9527dca9b523302b8409e154fb68e6a586b4e06d @TheNeikos ?

**Comment by TheNeikos** [comment]
Yup, that's how you fix it

**Comment by matthiasbeyer** [comment]
@TheNeikos thanks.
